// Add your favorite product with average price, proper unit, best category, modern icon and beautiful name
// Icons should download from Icons8 with 96*96 size and Windows 11 color filled:
// https://icons8.com/icons/fluency
let products = [
  {
    name: "بطری آب معدنی",
    price: 5_000,
    image: "bottle.png",
    unit: "عدد",
    category: "food",
  },
  {
    name: "میوه تازه",
    price: 40_000,
    image: "fruit.png",
    unit: "کیلو",
    category: "food",
  },
  {
    name: "آجیل تازه",
    price: 350_000,
    image: "nuts.png",
    unit: "کیلو",
    category: "food",
  },
  {
    name: "گوشت گوسفندی",
    price: 500_000,
    image: "meat.png",
    unit: "کیلو",
    category: "food",
  },
  {
    name: "آبمیوه طبیعی",
    price: 60_000,
    image: "juice.png",
    unit: "لیوان",
    category: "food",
  },
  {
    name: "بسته اینترنت",
    price: 4_000,
    image: "mobile-data.png",
    unit: "گیگ",
    category: "conections",
  },
  {
    name: "نان لواش",
    price: 600,
    image: "naan.png",
    unit: "عدد",
    category: "food",
  },
  {
    name: "برنج ایرانی",
    price: 90_000,
    image: "rice.png",
    unit: "کیلو",
    category: "food",
  },
  {
    name: "تخم مرغ",
    price: 50_000,
    image: "egg.png",
    unit: "کیلو",
    category: "food",
  },
  {
    name: "ماهی قزل آلا",
    price: 220_000,
    image: "fish.png",
    unit: "کیلو",
    category: "food",
  },
  {
    name: "مرغ تازه",
    price: 85_000,
    image: "chicken.png",
    unit: "کیلو",
    category: "food",
  },
  {
    name: "همبرگر ساده",
    price: 50_000,
    image: "hamburger.png",
    unit: "عدد",
    category: "food",
  },
  {
    name: "بستنی قیفی",
    price: 30_000,
    image: "icecream.png",
    unit: "عدد",
    category: "food",
  },
  {
    name: "سهام فولاد مبارکه",
    price: 750,
    image: "stock.png",
    unit: "سهم",
    category: "finance",
  },
  {
    name: "آمریکا",
    price: 65_000,
    image: "doller.png",
    unit: "دلار",
    category: "finance",
  },
  {
    name: "خانه در تهران",
    price: 70_000_000,
    image: "house.png",
    unit: "متر",
    category: "finance",
  },
  {
    name: "کتاب ارزشمند",
    price: 250_000,
    image: "book.png",
    unit: "عدد",
    category: "entertaiment",
  },
  {
    name: "ساعت مچی CASIO",
    price: 500_000,
    image: "watch.png",
    unit: "عدد",
    category: "clothes",
  },
  {
    name: "دوچرخه شهری",
    price: 7_000_000,
    image: "bicycle.png",
    unit: "دستگاه",
    category: "transport",
  },
  {
    name: "موتور سیکلت",
    price: 120_000_000,
    image: "bike.png",
    unit: "دستگاه",
    category: "transport",
  },
  {
    name: "تاکسی اینترنتی",
    price: 80_000,
    image: "taxi.png",
    unit: "کرایه",
    category: "transport",
  },
  {
    name: "قطار تهران - مشهد ",
    price: 600_000,
    image: "train.png",
    unit: "بلیط",
    category: "transport",
  },
  {
    name: "اتوبوس بین شهری",
    price: 150_000,
    image: "bus.png",
    unit: "بلیط",
    category: "transport",
  },
  {
    name: "خودروی پراید",
    price: 200_000_000,
    image: "pride.png",
    unit: "دستگاه",
    category: "transport",
  },
  {
    name: "بنزین",
    price: 3_000,
    image: "fuel.png",
    unit: "لیتر",
    category: "transport",
  },
  {
    name: "بلیط مترو",
    price: 4_300,
    image: "metro.png",
    unit: "عدد",
    category: "transport",
  },
  {
    name: "آیفون 15",
    price: 45_000_000,
    image: "iphone.png",
    unit: "دستگاه",
    category: "connections",
  },
  {
    name: "موبایل اندرویدی",
    price: 6_000_000,
    image: "phone.png",
    unit: "دستگاه",
    category: "connections",
  },
  {
    name: "لپ تاپ اقتصادی",
    price: 25_000_000,
    image: "laptop.png",
    unit: "دستگاه",
    category: "connections",
  },
  {
    name: "مک بوک اپل",
    price: 70_000_000,
    image: "macbook.png",
    unit: "دستگاه",
    category: "connections",
  },
  {
    name: "اشتراک تلگرام پریمیوم",
    price: 2_000_000,
    image: "telegram.png",
    unit: "سال",
    category: "connections",
  },
];